# --------------------
# Base image
# --------------------
FROM node:20-slim AS base

WORKDIR /app

# Install system dependencies for Puppeteer
RUN apt-get update && apt-get install -y \
    chromium \
    ca-certificates \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    xdg-utils \
    python3 \
    make \
    g++ \
    git \
    bash \
    --no-install-recommends && rm -rf /var/lib/apt/lists/*

# Puppeteer environment variables
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

# Copy package files first (for caching dependencies)
COPY package*.json ./

# Copy the rest of the code
COPY . .

EXPOSE 8080

# --------------------
# Production stage
# --------------------
FROM base AS production
ENV NODE_ENV=production

# Install only production dependencies
RUN npm ci --only=production

CMD ["npm", "start"]

# --------------------
# Development stage
# --------------------
FROM base AS dev
ENV NODE_ENV=development
ENV TZ="UTC"

# Install dev dependencies
RUN npm install
RUN npx prisma generate

CMD ["npm", "run", "dev"]
